name: leihladen_user_frontend_app
description: Das User Frontend

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^3.1.0
  shared_preferences: ^0.5.12+4
  badges: ^1.1.6
  http: ^0.12.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/katalog/json_daten_formatiert.json
    - assets/images/header/gemischtwaren_sepia.jpg
    - assets/images/header/hand_in_hand.jpg
    - assets/images/header/lastenrad.jpg
    - assets/images/header/zentrum.jpg
    - assets/images/symbol/a_z_symbol.png
    - assets/images/symbol/admin_symbol.png
    - assets/images/symbol/beliebt_symbol.png
    - assets/images/symbol/chat_symbol.png
    - assets/images/symbol/entliehen_symbol.png
    - assets/images/symbol/freizeit_symbol.png
    - assets/images/symbol/garten_symbol.png
    - assets/images/symbol/haushalt_symbol.png
    - assets/images/symbol/help_symbol.png
    - assets/images/symbol/home_symbol.png
    - assets/images/symbol/info_symbol.png
    - assets/images/symbol/kinder_symbol.png
    - assets/images/symbol/kueche_symbol.png
    - assets/images/symbol/message_symbol.png
    - assets/images/symbol/leihausweis_symbol.png
    - assets/images/symbol/multimedia_symbol.png
    - assets/images/symbol/order_symbol.png
    - assets/images/symbol/sachspende_symbol.png
    - assets/images/symbol/spiele_symbol.png
    - assets/images/symbol/sonstiges_symbol.png
    - assets/images/symbol/system_symbol.png
    - assets/images/symbol/warenkorb_symbol.png
    - assets/images/symbol/werkstatt_symbol.png
    - assets/images/symbol/wunschliste_symbol.png
    - assets/images/logos/dpl_logo_512.jpg
    - assets/images/logos/ic_launcher.png
    - assets/images/logos/ll_neues_logo.png
    - assets/images/logos/logo_buergerzentrum_haus_klein.png
    - assets/images/logos/logo_weiss_stadtfulda_klein.jpg
    - assets/images/logos/ll_neues_logo.png
    - assets/images/logos/map_dingelstedtstrasse.png
    - assets/images/logos/awo_logo.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
